### ISSUE TITLE
Git LFS error

### ISSUE THREAD

**Issue by alomrani** [JinheonBaek/KALMV#2]
Hi,

When trying to download the dataset jsonl files with git fetch lfs, I get the following error:
`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/alomrani/KALMV.git/info/lfs'`

Is there a way I can download the data from another source?

Secondly, how are entities.jsonl and relations.jsonl created?

Thanks,
Mohammad

**Comment by JinheonBaek** [comment]
Thanks for your interest, and we apologize for the inconvenience. 

We are unaware of the GitHub policy on constraints in distributing larger files. For the datasets, we have updated the guidelines in the README file and you can download them at the following OneDrive link: https://1drv.ms/f/s!Aj5JerV8SMDyi-tJ5QOlll_ksf1fRA?e=6HOmI2.

In addition, entities.jsonl and relations.jsonl are created from the Wikidata dump (Please see https://www.wikidata.org/wiki/Wikidata:Database_download).

**Comment by JinheonBaek** [comment]
I hope my previous update resolves your problem. Let me know if you encounter this error again.
