### ISSUE TITLE
 List of dependencies

### ISSUE THREAD

**Issue by Taekyo-Lee** [JinheonBaek/KALMV#3]
Hi Jinheon, 
Could you please upload the list of dependencies, for instance as requirements.txt?
Aren't there any others besides Python, PyTorch and transformers?

**Comment by JinheonBaek** [comment]
Thank you, Taekyo, for your interest. And, sure - you can now check the list of dependencies: https://github.com/JinheonBaek/KALMV/blob/main/requirements.txt

**Comment by Taekyo-Lee** [comment]
Thank you for your attention. Really interested in your work!!

**Comment by JinheonBaek** [comment]
Thanks. Happy Holidays. :)
