### ISSUE TITLE
questions about the  KGQA datasets

### ISSUE THREAD

**Issue by ROSC263** [JinheonBaek/KALMV#5]
Hi, JinheonBaek,

Thanks for your great work! 
I would like to kindly ask about the process of generating the KGQA datasets. If I want to work on WebQSP and Mintaka QA datasets based on Freebase, how can I generate datasets with the same structure as the one based on Wikidata?

**Comment by JinheonBaek** [comment]
Thank you for your interest! 

You can first download the full dump of the freebase (which is now deprecated though) and then match the entities in the dataset with the nodes in the freebase knowledge graph. I no longer have the code for preprocessing the freebase version of WebQSP but I hope you can easily reproduce it.

**Comment by ROSC263** [comment]
Thank you so much!
